// Code generated by hertz generator.

package main

import (
    "github.com/chenyuIT/framework/facades"
	"github.com/cloudwego/hertz/pkg/app/server"
	"chenyuIT/bootstrap"
)

func main() {
	bootstrap.Boot()
	//test function
	//加解密测试
	enstr, _ := facades.Crypt.EncryptString("hello")
	facades.Log.Debug(enstr)
	decodestr, _ := facades.Crypt.DecryptString(enstr)
	facades.Log.Debug(decodestr)

	//配置读取测试
	database_str := facades.Config.GetString("DB_DATABASE")
	// facades.Log.Debug(database_str)
	println(database_str)
	
	
    //Start Hertz Web Server on port 8888	
	h := server.Default()
	register(h)
	h.Spin()
}
